server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /sw.js {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }

  location = /manifest.webmanifest {
    default_type application/manifest+json;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
